### ISSUE TITLE
umxEFA does not return loadings

### ISSUE THREAD

**Issue by AgnerF** [tbates/umx#112]
Thanks for maintaining this code and for fixing issue #103. I am impressed how well umxEFA solves problems with missing values and how it can do a factor analysis with more variables than observations. It takes hours to calculate in my case, even without the summary, but the result is perfect.

Anyway, two new bugs have appeared since last time:
1) umxEFA returns the data matrix rather than the loadings unless you specify loadings="model".
2) umxEFA does not work with rotation methods from GPArotation, e.g. quartimax. The error message says "Error in t.default(rm) : argument is not a matrix".

**Comment by tbates** [comment]
I pushed a commit to `umxEFA` last week so that it returns scores by default when requested (used to require user to also set `return = "loadings"`) this and other edits might have fixed your issue. I'm can't replicate the issue with quartimax:

```R
x = umxEFA(mtcars[, myVars], factors = 2, rotation = "quartimax", return = "loadings")
[1] "Rotation results"
Orthogonal rotation method Quartimax converged.
Loadings:
         F1     F2
mpg  -0.893  0.135
disp  0.914 -0.140
hp    0.756 -0.530
wt    0.968  0.177
qsec -0.327  0.833

Rotating matrix:
      [,1]   [,2]
[1,] 0.989 -0.149
[2,] 0.149  0.989

```

**Comment by tbates** [comment]
Could add a note to people who want the full-Monty to use `mxFactorScores` which returns this attributed 3-D matrix:

```R
 num [1:50, 1, 1:2] -0.167 -0.106 -2.137 -0.157 1.106 ...
 - attr(*, "dimnames")=List of 3
  ..$ : chr [1:50] "1" "2" "3" "4" ...
  ..$ : chr "G"
  ..$ : chr [1:2] "Scores" "StandardErrors"
```

Is there also an example paper doing something with SEs, I could cite that.
