### ISSUE TITLE
umxModify: Add autorun argument

### ISSUE THREAD

**Issue by bwiernik** [tbates/umx#13]
I'd like to use the regex functionality in umxModify to make a series of changes to a model. I'd like to not have the optimizer run each time I make one change. Could the autorun argument be added to this function with default=TRUE?

**Comment by tbates** [comment]
done :-)
I've been wondering, would it be helpful to let regex take a list, and have umxModify act on each pattern in turn.

Might make it easier to write simple reg-ex's, e.g. to match 1 and 2-digit column and row labels.

**Comment by bwiernik** [comment]
Thanks!

"Sometimes you have a problem and think that regex would be a good solution. Then, you have two problems."

I generally find regex complex and fussy enough to use that I wouldn't want to try to build multi-step modification chains with them. But I could see the potential value for some users. 

For the specific case you mention, wouldn't "a_[1-9]+" be sufficient?

**Comment by tbates** [comment]
FYI, `umxModify(, autoRun=T|F)`  is in the umx 1.5.5 CRAN release

    umx_open_CRAN_page("umx")
