### ISSUE TITLE
regex support on umxCI

### ISSUE THREAD

**Issue by khusmann** [tbates/umx#135]
Would be a nice feature! (Esp for adding CIs on things in multigroup contexts)

Or is there an existing easy way to do it?

**Comment by tbates** [comment]
done: Thanks for the smart suggestion!

```R
require(umx)
 data(demoOneFactor)
 manifests = names(demoOneFactor)
 m1 = umxRAM("One Factor", data = demoOneFactor, type = "cov",
 	umxPath("G", to = manifests),
 	umxPath(var = manifests),
 	umxPath(var = "G", fixedAt = 1)
 )

parameters(m1, patt="_with_")
m1 = umxCI(m1, regex = "x1_with_", run= "yes")
```

|            | lbound | estimate | ubound | lbound | Code |
|:-----------|:-------|:---------|:-------|:-------|:-----|
| x1_with_x1 | 0.036  | 0.041    | 0.047  | 0      | 0    |

**Comment by khusmann** [comment]
wow, that was quick -- thanks for the fast change!
