### ISSUE TITLE
warning messages when specifying lists of confidence intervals

### ISSUE THREAD

**Issue by khusmann** [tbates/umx#136]
Hi, it's me again :)

Getting these warning messages when specifying lists of confidence intervals:

```
require(umx)
data(demoOneFactor)
manifests = names(demoOneFactor)
m1 = umxRAM("One Factor", data = demoOneFactor, type = "cov",
	umxPath("G", to = manifests),
	umxPath(var = manifests),
	umxPath(var = "G", fixedAt = 1)
)
m1 = umxCI(m1, c("x1_with_x1", "x2_with_x2"), run= "yes")
```

Output is as expected, but with warnings:
```
1: In if (is.na(which)) { :
  the condition has length > 1 and only the first element will be used
2: In if (which == "ALL") { :
  the condition has length > 1 and only the first element will be used
```

Looks like those are coming from 
https://github.com/tbates/umx/blob/master/R/fit_and_reporting.R#L754 and https://github.com/tbates/umx/blob/master/R/fit_and_reporting.R#L738

Perhaps there should be a different arg-checking flow when `which` is a vector?

**Comment by tbates** [comment]
should have had a test case for that. Fixed now!

**Comment by khusmann** [comment]
Thanks!!
