### ISSUE TITLE
umxRAM modify existing model

### ISSUE THREAD

**Issue by khusmann** [tbates/umx#138]
This is either a bug or I'm not understanding how to use umxRAM to modify paths:

```
manifests = paste0("x", 1:3) # "x1" "x2" "x3"
latents = c("A", "B")

m1 <- umxRAM("m1", data = myFADataRaw,
	# 1-headed paths from latent B to each of the manifests
	umxPath("B", to = manifests),
	# A slightly silly unit-covariance between latent 1 & 2
	umxPath("A", with = "B", fixedAt = 1),
	# free mean and variance for the manifests and standardized latents.
	umxPath(v.m. = manifests),
	umxPath(v1m0 = latents)	
)
```
then

```
m2 <- umxRAM(model=m1, umxPath("A", with = "B", fixedAt = 4))
```

Errors with: `Error: In umxRAM, you must set 'data = '. If you're building a model with no data, use mxModel`

Interestingly, dummy values for data work:
```
m2 <- umxRAM(model=m1, data=NA, umxPath("A", with = "B", fixedAt = 4))
```

Should I just be using mxModel to add paths to existing models? (Or umxModify?)

As a side note, I was hoping to use umxRAM in my use case to take advantage of the ability to specify a suffix for paths. But right now it doesn't look like any of these ways to add paths automatically names them with umx-style names, they just show up blank.

**Comment by tbates** [comment]
For what you're attempting, I think I would "just" ask the first creator to add suffixes then just free the path with `umxModify`, e.g. 
```R
m2 = umxModify(m1, "A_with_B", fixedAt = 4))
``` 

If I get you right?  If not, sing out again.


I don't use the `umxRAM` to update models very often: it's quite restrictive. But I see the bug you found: we don't need data.

It's **Fixed now**, and should also function to replace the data in an existing model if you pass in model and data.

Not knowing how to do labels and values without knowing how the original model was built was one reason I found it easier to start fresh rather than modify an existing model.

This still doesn't label the new path, that would basically mean adding a way to detect new paths, and just label them, Will add to the todo list if it seems useful?

But this will work just fine:

```R
m2= umxRAM(model=m1, umxPath("A", with = "B", fixedAt = 4, labels = "A_with_B_suffix"))
```

**Comment by khusmann** [comment]
> But I see the bug you found: we don't need data. It's Fixed now

Awesome, thanks!

> I don't use the umxRAM to update models very often: it's quite restrictive.

Yeah, that's the same conclusion I've some to after fiddling more with it. What I was wanting to do was build models in a more modular, reusable, and composable way. I think I've found a neat pattern using lists of paths:

```
library(umx)
library(tidyverse)

base_model <- function(model_def) {
  list2env(model_def, environment())
  c(
    # 1-headed paths from latent B to each of the manifests
    umxPath(F1, to = manifests),
    # free mean and variance for the manifests and standardized latents.
    umxPath(v.m. = manifests),
    umxPath(v1m0 = F1) 
  )
}

add_silly_factor <- function(model_def) {
  list2env(model_def, environment())
  c(
    # A slightly silly unit-covariance between latent 1 & 2
    umxPath(F2, with = F1, fixedAt = 1),
    umxPath(v1m0 = F2)
  )
}

build_model <- function(name, data, model_def) {
  st <- flatten(map(model_def$structure, exec,
                    model_def = model_def))
  exec("umxRAM", name, data=as.data.frame(data), !!!st)
}

m1 <- build_model("m1", 
  data = myFADataRaw,
  model_def = list(
    manifests = paste0("x", 1:3),
    F1 = "B",
    F2 = "A",
    structure = c(
      base_model,
      add_silly_factor
    )
  )
)
```

This way I can easily toggle `add_silly_factor` on and off, or easily run the same model on a different data set (especially useful for complex models). I'm still playing around to see if I actually like this approach.

> This still doesn't label the new path, that would basically mean adding a way to detect new paths, and just label them, Will add to the todo list if it seems useful?

That might be interesting -- I think it would allow this same kind of approach but with a little less boilerplate? I'm not sure it's worth it though, because you'd also have to detect when to add new columns too... (you could use remove_unused_manifests, but it seems like you'd start opening a can of worms going down this path)

I think what would be maybe more useful is to have the umxRAM `suffix` parameter act on labels which would simplify this approach in multigroup contexts (what I mentioned here would work in this context too: https://github.com/tbates/umx/issues/67#issuecomment-659041550 ).

**Comment by tbates** [comment]
Given that all possible paths already exist and have labels in a umxRAM model (and any change in the columns of data will require re-building the whole model), it's unclear adding a path via umxRAM is needed when umxModify can free and re-label paths ad-lib. Given `umxModify` and all the extra work that `umxRAM` does compared to `mxModel` (which does no labelling, value-setting, data mx-ification etc, etc) the OpenMx workflow of `mxModel(mxModel(...), ...)` just isn't efficient or transparent in `umRAM`.

I'll close this for now - feel free to reopen or make a new issue if desired.

**Comment by khusmann** [comment]
Makes sense, thanks!
