### ISSUE TITLE
umxPlotGxE - export ggplot

### ISSUE THREAD

**Issue by tbates** [tbates/umx#139]
give user a gg= TRUE option, exporting a ggplot2 graph which they could then decorate/alter

- [x] replace/enhance existing matplot code with ggplot call

https://openmx.ssri.psu.edu//node/4667

**Comment by tbates** [comment]
<img width="743" alt="GxE plot 2020-10-06 at 10 24 44" src="https://user-images.githubusercontent.com/736156/95183669-34720380-07be-11eb-93bc-b1077227f9b9.png">

**Comment by mcneale** [comment]
Very nice - but IMO it’s much more important to show unstandardized estimates.

**Comment by tbates** [comment]
> Very nice - but IMO it’s much more important to show unstandardized estimates.

Which is why we do both and explain why unstandardised is so much more informative 😀😎

**Comment by mcneale** [comment]
Yep, so only post graphs of unstandardized please!  If you add CIs it would be great. 

I think ALL GxE of complex traits (measured by items) should be forced to publish a Test Information Curve for the outcome measure alongside the findings.  It’s way too easy to be fooled into thinking gxe when it’s simply a measurement artifact.

**Comment by tbates** [comment]
43 issues ago... https://github.com/tbates/umx/issues/96

feel free :-)
