### ISSUE TITLE
graphics: Allow saving as png/pdf

### ISSUE THREAD

**Issue by tbates** [tbates/umx#149]
Be nice to allow users to save SEM diagrams as SVG or png etc. instead of web screenshots or needing omnigraffle to import .dot files.

`DiagrammeR` supports integrating with rsvg, so it's straightforward, e.g.

https://github.com/rich-iannone/DiagrammeR/issues/330

**Comment by tbates** [comment]
OK: svg, pdf, png now supported as `plot()` outputs with

```R
umx_set_plot_format(“pdf”) # or png or svg, etc.
```

**Comment by lf-araujo** [comment]
Hi Tim, 

not sure if I should open new issues, but

```{r}
plot(model_run)
```

will not be kept in the final rmarkdown output. Is this by design? It only opens the browser with the image and the final document only shows the code.


Also, it does not follow knitr filesystem settings, code such as:

```
# Knitr options
knitr::opts_chunk$set(
  fig.path = "../graphs/", # where should I save figures?
  dpi = 300 # high dpi for publication quality
) 
```


Will not have any effect even after 

```
umx_set_plot_format("png")
```


Best

**Comment by tbates** [comment]
`umx_set_plot_format("png")` is working as designed me (plots written as png  into `getwd()`, open in preview.app (on MacOS))
What OS are you using? Are .png files ending up in `getwd()`?

I could look at using opts_chunk$get("fig.path") from knitr,  but the great majority of umx users don't use knitr for anything other than kable().  I'll have a think about how this might work.

t

**Comment by lf-araujo** [comment]
Thanks Tim,

The pngs are being saved in the getwd() folder, so this is working as you intended. I understand most openMx users are not using knitr and rmarkdown, but these are very interesting tools to communicate results between researchers. I further tested umx and will provide fully minimal working examples below, and noticed that  umx.plot() works when hml_notebook is used, but does not in all other outputs.

What I mean by working is to include the image in body of the final .docx, .html document.

So rendering following example does not work:


```r
---
title: Attempt to use lav2ram
author: lf-araujo
---

```{r setup, include=FALSE}
dep <- function(x) {
  ifelse(!all(x %in% installed.packages()),
    install.packages(x[x %in% installed.packages()[, "Package"] == F],
      repos = "http://cran.us.r-project.org"
    ),
    lapply(x, require, character.only = T)
  )
}

dep(c(
  "ProjectTemplate", "summarytools", "here", "visdat",
  "naniar", "ggplot2", "tidyverse", "umx", "knitr"
))

set.seed(42) # setting seed for stochastic functions
setwd(here()) # needed as we are in /src, in linux here() should be used

load.project() # Loading the project

# R options
options(
  digits = 2, # Only two decimal digits
  scipen = 999
) # Remove scientific notation

# OpenMx use of cores
mxOption(key = "Number of Threads", value = parallel::detectCores())
mxOption(key = "maxOrdinalPerBlock", value = 200)
# Umx settings
umx_set_table_format("markdown")
umx_set_auto_plot(autoPlot = F)

# Knitr options
opts_chunk$set(
  comment = NA, # remove comment symbol
  cache.path = "../cache/", # where should I save cache?
  fig.path = "../graphs/", # where should I save figures?
  echo = T, # dont echo by default
  cache = F, # dont cache by default
  fig.width = 10, # setting the best witdth for figures
  fig.height = 7, # best height
  dpi = 300
) # high dpi for publication quality
```

```{r model}
model <- "
x2 + y2 ~ x1
y2 + x2 ~ y1

x1 ~~ y1
x2 ~~ y2

x1 + x2 ~ d
y1 + y2 ~ u


# variances
x1 ~~ 1*x1
x2 ~~ 1*x2
y1 ~~ 1*y1
y2 ~~ 1*y2
d ~~ 1*d
u ~~ 1*u
"
```

Simulating data
---------------

```{r simulate}
m1 <- umxRAM(model)
simData <- mxGenerateData(m1, nrows = 1000, returnModel = TRUE)
```

Checking identification
-----------------------

```{r}
mxCheckIdentification(m1, details = T)
```

Now Plot!
---------

```{r}
plot(m1)
```

```

Now it will work if you add one line to the yaml header: `output: html_notebook`

**Comment by tbates** [comment]
What code would I add to get you running as desired?

`plot` takes a `file` parameter, but it seems like what we want is for `plot` to look into the environment for `opts_chunk` and, iff it is set, use the contents to guide plotting?  

```R
opts_chunk$get()$fig.path
[1] "../graphs/"
```
Maybe also pull the  fig.width, fig.height = 7, and dpi when they can be passed along.

PS: How does knitr set the titles for figures?


PPS:: Wish `R` supported `dep`'s "load, doing whatever's necessary" functionality (umx does this with `libs`. That and a `+=` operator :-)

**Comment by lf-araujo** [comment]
> What code would I add to get you running as desired?

I wish I was as good a programmer! I dont't really know how to plug this functionality into knitr, very sorry.

> plot takes a file parameter, but it seems like what we want is for plot to look into the environment for opts_chunk and, iff it is set, use the contents to guide plotting?

I think both functionalities are very useful: a. saving the png/tiff file if opts_chunk is set; and b. including the image in the document, which only works on rnotebooks (aka html_notebook) atm.

> Maybe also pull the fig.width, fig.height = 7, and dpi when they can be passed along.

This would be great!

> PS: How does knitr set the titles for figures?

For figures, you can set the label in the chunk heading: {r fig.cap="This is where the dandy label goes")

> PPS:: Wish R supported dep's "load, doing whatever's necessary" functionality (umx does this with libs. That and a += operator :-)

Will look into this, thanks. There is an anonymous version too: 

```
(function(x) {
  ifelse(
    !all(x %in% installed.packages()),
    install.packages(x[x %in% installed.packages()[, "Package"] == F]),
    lapply(x, require, character.only = T)
  )
})(c(
  "ProjectTemplate", "summarytools", "here", "visdat",
  "naniar", "ggplot2", "tidyverse", "umx", "knitr"
))
```

**Comment by tbates** [comment]
Can you try the devtools:install_github("tbates/umx")` version?

This works for me now, in that knitr captures the `plot` output without umx needing to do anything.

````r
---
title: "test.Rmd"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(umx)
```

## Model & table

```{r comment="", results='asis'}

mtcars$litres = mtcars$disp/61.02
m1 = umxRAM("tim", data = mtcars,
	umxPath(c("wt", "litres"), to = "mpg"),
	umxPath("wt", with = "litres"),
	umxPath(v.m. = c("wt", "litres", "mpg"))
)
```

## A umx Plot

```{r}
plot(m1)
```

````

**Comment by lf-araujo** [comment]
Thanks Tim,

Sorry for the late reply.

Yes, I can confirm this is working for html_document and for html_notebook, which solves the problem.

- If you have the time you can try to make this also work in word_documents, but it is much harder as the graphviz output is html only. Perhaps printing out a tmp png file and then passing on to pandoc?

But for the initial comment, this issue seems to be solved.
