### ISSUE TITLE
Add a means table print out to umxSummary

### ISSUE THREAD

**Issue by tbates** [tbates/umx#15]
It would be useful for users to be able to get a table of means (just as they can request genetic correlations with `showRg= TRUE` now)

for twins, where we now print:

|    |    a1|c1 |    e1|
|:---|-----:|:--|-----:|
|wt1 | -0.83|.  | -0.56|

We could do:

|      |      a1|c1 |    e1|  mean|
|:---|-----:|:--|-----:|-----:|
|wt1 | -0.83|.  | -0.56|  75.3 |

**Comment by mcneale** [comment]
Yep.  I think printing zero or .00 would be much better than a . which some  software (cough, SAS) might interpret as a missing value.

On Mar 29, 2017, at 9:27 AM, Tim Bates <notifications@github.com<mailto:notifications@github.com>> wrote:


It would be useful for users to be able to get a table of means (as they can get genetic correlations etc)

for twins, where we now print:
| | a1|c1 | e1|
|:---|-----:|:--|-----:|
|wt1 | -0.83|. | -0.56|

We could do:
        . a1    c1      e1      mean

wt1     -0.83   .       -0.56   75.3

**Comment by tbates** [comment]
Interesting: I wrote a special print function to suppress 0.00 to make (esp. larger ACE tables full of zeros) tables easier to read.

I'll add a TODO to add an option to set this place-keeper to whatever symbol the user desires.

factor analysis has it's own print method which allows suppressing small values, and they just print blank. so could follow that model.

**Comment by tbates** [comment]
this is now in place for umxACE, and some other models.
means tables also can be report="html" tables for copying to a word processor.
