### ISSUE TITLE
Differences between confint, umxCIand umxConfint?

### ISSUE THREAD

**Issue by lf-araujo** [tbates/umx#152]
Dear Tim,

Thanks for the package!

I am having difficulties understanding which confidence interval to report in my analyses. Currently working on an ACE,

- What are the differences between confint(), umxCI() and umxConfint()?

Thank you.

**Comment by tbates** [comment]
thanks!

`confint` gives SE-based confidence intervals (WALD type CIs).

`umxCI()` gives likelihood-based CIs, which are superior, but usually similar to the SE-based CIs. They can be asymmetric, as the `umxCI` actually explores how parameter changes drop the model fit. This can also make them time consuming to compute.

`umxConfint` I think you can ignore - it's an solution from early in umx's development which  I haven't yet rolled into umxCI and deprecated.

usability suggestions welcome
t

**Comment by lf-araujo** [comment]
Thanks Tim for this, I think in terms of usability there is nothing I would change.
