### ISSUE TITLE
make a function to rename models so they can be included in a super model

### ISSUE THREAD

**Issue by tbates** [tbates/umx#157]
A common task is seeing if a model fits more than one dataset - e.g. for replication, or generalisability, or meta-analysis.

`umxSuperModel` can combine groups (at least when  #156 is closed), but the groups have the same model names, then the model won't run. SO... need to trundle over the 2nd through nth models suffixing their model names with n...

- [x] Detect if user adds models with the same name to umxSuperModel...
- [x] Create unique name function
- [x] Call this in `umxSuperModel`

**Comment by mcneale** [comment]
It is the most attractive function name in the package!  All models are hot, some models are super hot...

**Comment by tbates** [comment]
`umxModelNames` added

**Comment by tbates** [comment]
`umxSuperModel` looks like a RAM model to `plot(m1)`, so a super model containing, say twin models in two data sets returns an error when plotting: `Error in eval(result, envir = env) : object 'S' not found`

Be nice to allow plot to detect RAM models which are just containers, and then plot the contents of non-RAM models, as it does now for multi-group RAM.

**Comment by tbates** [comment]
`mxRefModels` can't handle WLS or twin models. Be nice to code around that for supermodels which contain twin models... would allow `umxSummary` to work for these also.
