### ISSUE TITLE
teaching: allow tmx_show to teach users about twin models, as well as umxRAM models

### ISSUE THREAD

**Issue by tbates** [tbates/umx#162]
Background: `tmx_show` can show the internals of umxRAM models with color and roll-over enhanced web tables.
Goal: Enable this for each twin model, so users can see

1. The groups and supergroup objective
2. Matrices in each group, their shape, values, lables
3. Algebras: their intended shape and formula
4. How information flows in and out of these components as wires conecting matrices to algebras, and these to objectives etc.
5. Graphical display of constraints

**Comment by tbates** [comment]
Few Twin users need/want this

**Comment by mcneale** [comment]
A pity, seems like it would have been pretty cool.

**Comment by tbates** [comment]
Just a polite way of saying Boulder is kaput :-)
