### ISSUE TITLE
umxSummarizeTwinData  add age= and check for presence of age  columns

### ISSUE THREAD

**Issue by tbates** [tbates/umx#164]
Maybe add 'age' as an argument, or give user a warning that age is missing?

The function looks for "age" or "age[separator]1" columns in the dataset

```R
data(twinData)
twinData[ , c("age","age1","age2")] <- list(NULL)

umxSummarizeTwinData(twinData, sep = "", selVars = c("wt", "ht"), MZ = MZs, DZ = DZs)
```
produces the following:

> Error in `[.data.frame`(data, , paste0("age", sep, 1)) : 
  undefined columns selected

**Comment by tbates** [comment]
try GitHub version now

**Comment by mcneale** [comment]
IMO "undefined columns selected" sucks as an error message.  R should do better.  It **knows** WHICH variable(s) are not found, but does it tell you which ones (out of possibly thousands of possibilities)?  No.  Bad programmer, go back to school, do not collect $200.

**Comment by tbates** [comment]
done

**Comment by tbates** [comment]
Just as a codicil to this issue, most umx functions use `umx_check_names`, allowing:

```R
umx_check_names(c("mpg", "meaning of life"), mtcars)
```
> Error in umx_check_names(c("mpg", "meaning of life"), mtcars) : 
  Not all required names were found in the data. Missing were:
meaning of life
