### ISSUE TITLE
It would be nice if umxPower accepted dropping more than one path

### ISSUE THREAD

**Issue by lf-araujo** [tbates/umx#167]
Code such as:

```r
umxPower(
  trueModel = CLPM_run, update = c("bxy12", "byx12"),
  sig.level = .05, explore = T
) 
```

Generates the error:

`Error: The 'name' argument must be a single character argument in mxRename(retval, name)`

Also, plotting is not implemented.

**Comment by mcneale** [comment]
I confirm that this is a bug.  Try replacing name = paste0("drop_", update)  with name = paste0("drop_", update[1]) in both places in umxPower() that it occurs.

**Comment by tbates** [comment]
Thanks for reporting @lf-araujo ! And thanks for the eyes @mcneale !

I now  `collapse` the update string now, when building a new name - just didn't try no more than one path change.

try ```devtools:install_github("tbates/umx")``` for the new version

t

**Comment by tbates** [comment]
OK, I now plot (by default) when `explore = TRUE`.

What else would be useful? On the TODO is to add a vertical line at N yielding power = .8

![power now](https://user-images.githubusercontent.com/736156/134154363-0eb9e17c-e107-42fa-a1ce-8bac5e8fa621.png)

When explore is F, the output is just a point estimate of power, so nothing to plot:

> 'result.mxPower' num 1
> attr(*, "detail")=List of 5
>   ..$ method   : chr "ncp"
>   ..$ sig.level: num 0.05
>   ..$ statistic: chr "LRT"
>   ..$ n        : num 400
>   ..$ power    : num 1

**Comment by tbates** [comment]
FYI, here's what ```plot(pwr::pwr.r.test(power=.8,r=.3))``` does, which has been my target for consistency.

![power e g](https://user-images.githubusercontent.com/736156/134154490-9ed3f2e6-8523-4087-8406-3f715c76de4f.png)

**Comment by tbates** [comment]
![power](https://user-images.githubusercontent.com/736156/134271316-b6d5c304-a355-4228-b1ab-2ec7099ae2d2.png)

**Comment by tbates** [comment]
![power](https://user-images.githubusercontent.com/736156/134271389-e3aa2365-5157-4cd2-8f3e-2248391a7baf.png)

**Comment by mcneale** [comment]
Very nice!  The other pieces of info that would be good to include in the Figures are: i) true model’s parameter values (i.e., effect sizes) and ii) the values to which the parameters were fixed.  The second should be easy enough (List (singular) of changed paths: “X_with_Y = 0”  and the first could also be reported as a list.  Yep, I’m being greedy, but this is an important function.  Now I think about it, a single table with parameter name, sim value, and fixed value could cover both.
