### ISSUE TITLE
Sketch mode for latent variables

### ISSUE THREAD

**Issue by lf-araujo** [tbates/umx#168]
Sketch mode is very handy while we are exploring theory. However, it seems it does not support sketching models with latent variables. From the help:

*Sketch mode*

     If you are at the "sketching" stage of theory consideration, ‘umxRAM’
     supports a simple vector of manifest names to work with.

     m1 = umxRAM("sketch", data = c("A", "B", "C"),
             umxPath("A", to = "B"),
             umxPath("B", with = "C"),
             umxPath(v.m. = c("A", "B", "C"))
     )

It would be nice to have something like:

     m1 = umxRAM("sketch", manifests=manifests, latents=latents
             umxPath("A", to = "B"),
             umxPath("B", with = "C"),
             umxPath(v.m. = c("A", "B", "C"))
     )

**Comment by tbates** [comment]
Hi @lf-araujo 
This is already supported, so I clarified the help and example: 

PS: Sketch is also useful for making data: just set the values you want, and `mxGenerateData` the data.

```R
m1 = umxRAM("sketch", data = c("A", "B"),
 	umxPath("C", to = c("A", "B")),
 	umxPath("A", with = "B"),
 	umxPath(v.m. = c("A", "B")),
 	umxPath(v1m0 = "C")
 )

```
<img width="292" alt="image" src="https://user-images.githubusercontent.com/736156/134437017-e1fc447c-e738-4ca4-9ee8-1c714478c4e4.png">
