### ISSUE TITLE
umxDOC with ordinal variables

### ISSUE THREAD

**Issue by lf-araujo** [tbates/umx#175]
Hi Tim,

I was experimenting with the umxDoC function and noticed it seems not to work with ordinal variables, my testing data set looks like:

![image](https://user-images.githubusercontent.com/10139950/141374907-3306de16-68ac-4fc1-8cde-f66c70198bad.png)

My code:

```r
doc <- umxDoC(
  sep = "_t",
  mzData = mzData,
  dzData = dzData,
  var1Indicators = c("anx", "dr", "eat", "dep", "adhd"),
  var2Indicators = c("dm", "hd", "hch", "hbp", "art", "cbp", "all", "res", "mig", "epi")
)
```

Which errors with: 

![image](https://user-images.githubusercontent.com/10139950/141375037-0a5b2d21-c60e-4ead-bb37-bbfaa79f6887.png)

- What am I doing wrong?

---

Also, I see that umxDoC is less flexible  on its calls, compared to umxCP. It loses the ability to pass the data set directly, like:

```
m2 <- umxCP(
  name = "2fac",
  data = dt,
  sep = "_t",
  selDVs = selDVs,
  mzData = "1: monozygotic",
  dzData = "2: dizygotic",
  nFac = 2
)
```

Is this by design? I think the above is quicker to write (and to pipe to and from) than splitting the data beforehand.

**Comment by lf-araujo** [comment]
Hi Tim,

Found that the DoCp works as intended regarding ordinal variables. 

---

Now, I took this opportunity to try a pull request that adds the data, zyg arguments to umxDoC. First ever PR, so please recheck. It works locally.

Best,
luis

**Comment by lf-araujo** [comment]
Thanks so much for the merge. This is very cool. Sorry for the assignments (<-) and the lack of @param, now I get it. I will get the hang of it over time. 

Now, in umxDoCp, the part:

```r
		# 5. ✓ Load specifics onto var1 and var2 indicators
		umxPath(as, to = c(var1Indicators, var2Indicators), values = .6),
		umxPath(cs, to = c(var1Indicators, var2Indicators), values = .6),
		umxPath(es, to = c(var1Indicators, var2Indicators), values = .6, lbound=1e-5),
```

Is it really correct, considering the model you are trying to specify?

![DoC](https://user-images.githubusercontent.com/10139950/144125466-b99caa45-6ce4-4dc6-abbc-970e4c950d21.png)

- What am I missing?

**Comment by tbates** [comment]
great! It's a fun if somewhat arduous learning curve.

The model should be drawn as below (I tried to keep the models clean and easy to see, but didn't always draw, for instance, all twin groups, or all residuals (your question), or fixed @1 variances. net net, I think that was a mistake.

So sprint goal: Upload a figure that's closer to "what we show is every path in the diagram" tonight.

![DoC](https://user-images.githubusercontent.com/736156/144134276-e053f71a-aacd-4932-868f-7255db1c8328.png)
