### ISSUE TITLE
compatibility 

### ISSUE THREAD

**Issue by gzhai** [tbates/umx#189]
> data(twinData)
> dz = subset(twinData, zygosity == "DZFF" & cohort == "younger")
> mz = subset(twinData, zygosity == "MZFF" & cohort == "younger")
> m1 = umxACE(selDVs = c("wt"), sep = "", dzData = dz, mzData = mz)
**Error in umxACE(selDVs = c("wt"), sep = "", dzData = dz, mzData = mz) : 
  could not find function "umxACE"**

**Comment by mcneale** [comment]
library(umx) or require(umx) is needed before using any of its functions.

**Comment by gzhai** [comment]
yes, I know. It is actually a version compatibility issue, it works with OpenMx version 2.19.8 but not with 2.20.0. And there are some issues to install the old version of OpenMx from the CRAN into Rstudio cloud, but Rstudio package manager helps to install the old version and the problem solved!

**Comment by mcneale** [comment]
Ah, yes, we are working on some compatibility issues.  BTW a bit more text with the initial post would have revealed the issue to be incompatibility rather than forgetting to invoke the library.

**Comment by tbates** [comment]
This is running fine for me under 
`umxVersion()  4.11.0, OpenMx  2.20.0,  R 4.1.2

```R
data(twinData)
dz = subset(twinData, zygosity == "DZFF" & cohort == "younger")
mz = subset(twinData, zygosity == "MZFF" & cohort == "younger")
m1 = umxACE(selDVs = c("wt"), sep = "", dzData = dz, mzData = mz)

Running ACE with 4 parameters
```

ACE -2 × log(Likelihood) = 12186.278


Table: Standardized parameter estimates from a 1-factor Cholesky ACE model. A: additive genetic; C: common environment; E: unique environment.

|   |    a1|c1 |    e1|
|:--|-----:|:--|-----:|
|wt | 0.922|.  | 0.388|


Table: Means (from model$top$expMean)

|          |    wt1|    wt2|
|:---------|------:|------:|
|intercept | 57.185| 57.185|
