### ISSUE TITLE
Specifying a mixture model?

### ISSUE THREAD

**Issue by jrosen48** [tbates/umx#19]
Thank you for creating (and documenting so well) such an excellent package. I'm currently trying to specify a mixture model (specifically, for Latent Profile Analysis or Latent Class Analysis). After surveying the available options in R, it looks like OpenMx may generally be the best way to carry it out, and umx seems like the best way to use OpenMx. 

I read some of the OpenMx documentation on how to specify mixtures / classes (i.e., [here](http://openmx.psyc.virginia.edu/docs/OpenMx/latest/GrowthMixtureModel_Path.html#mixture-modeling), and after reviewing the help (and reading through the specification for [multiple group models](http://tbates.github.io/advanced/1995/02/15/detailed-Multigroup.html), which is close but if I understand correctly a bit different from discovering the classes or mixture components, am wondering if you could point me in the right direction for whether - and if so how - you could specify this using `umx`... functions.

**Comment by tbates** [comment]
more a question for https://openmx.ssri.psu.edu/forums/opensem-forums/mixture-distribution-and-latent-class-models
