### ISSUE TITLE
https://tbates.github.io docs

### ISSUE THREAD

**Issue by lf-araujo** [tbates/umx#190]
Hi Tim,

Came across the following. In the documentation, you mention:

![image](https://user-images.githubusercontent.com/10139950/154145828-0d9d8e50-52cb-4b16-a447-07acd5ada3fb.png)

However if I start R and umx anew, I get:

![image](https://user-images.githubusercontent.com/10139950/154146051-5b760190-dd3d-4ba7-9c9d-51c6dad20ca3.png)

**Comment by RMKirkpatrick** [comment]
SLSQP has been the on-load default optimizer since [OpenMx 2.18](https://openmx.ssri.psu.edu/node/4657).  I think umx's documentation needs to be updated.

**Comment by tbates** [comment]
thanks @lf-araujo fixed! 

https://tbates.github.io/technical/1943/02/12/technical-Optional-optimizers.html

I've been remiss in updating the tbates.github.io site: Any other out of date code or just request, do post here and I will fix promptly.

**Comment by lf-araujo** [comment]
It may be related to the fact I am running this on Linux? Never really was able to install NPSOL in my machine, so I wasn't surprised it didn't come up as an option.
