### ISSUE TITLE
umxGxE function - error in slot

### ISSUE THREAD

**Issue by salvatoj** [tbates/umx#191]
Hello - I am getting an error message with the sample data/script for the umxGxE function "Error in slot(value, what) : 
  no slot of name "runstate" for this object of class "MxModel". Might you be able to advise on how to fix?

https://search.r-project.org/CRAN/refmans/umx/html/umxGxE.html

**Comment by RMKirkpatrick** [comment]
This might actually be OpenMx-related.  Have you updated to OpenMx 2.20.3?  It's currently available via CRAN.

**Comment by salvatoj** [comment]
That fixed it - thanks Rob!
