### ISSUE TITLE
no slot of name "runstate" for this object of class "MxModel" error in Jupyter lab

### ISSUE THREAD

**Issue by arinbasu** [tbates/umx#198]
Hi Tim,
I ran the following umxACE model in a Jupyter lab 
```
data(twinData)
selDVs = c("bmi")
dz = twinData[twinData$zygosity == "DZFF",]
mz = twinData[twinData$zygosity == "MZFF",]
m1 = umxACE(
    selDVs = selDVs,
    dzData = dz,
    mzData = mz,
    sep = ""
    )
summary(m1)
```
This produced the following error:
`Error in slot(value, what): no slot of name "runstate" for this object of class "MxModel" `

**Comment by RMKirkpatrick** [comment]
You may need to update umx.  The 'runstate' slot was eliminated from the MxModel class definition in OpenMx v2.20.

**Comment by RMKirkpatrick** [comment]
> It's because the model has not yet been run.

That's not why.  umx's on-load default behavior is to automatically run a umx model after it's created.

**Comment by arinbasu** [comment]
Thanks Rob and Mike.
I uninstalled `umx` and reinstalled it with
`devtools::install_github("tbates/umx")`
With the current version of OpenMx (2.20.6.6), the problem is now resolved.
Thank you again for your fast solution. 
I will close this issue now.

**Comment by RMKirkpatrick** [comment]
Glad to help.
