### ISSUE TITLE
umxMendelianRandomization help can't be invoked currently

### ISSUE THREAD

**Issue by lf-araujo** [tbates/umx#209]
Hi Tim,

Came across this:
`?umxMendelianRandomization`  doesn't work, but  `?umxTwoStage` works

![image](https://user-images.githubusercontent.com/10139950/202225386-e9e1ad0a-6dc0-4c87-a8fc-94febacbb9f3.png)

**Comment by tbates** [comment]
yeah, I vacillated over what to call it, and ended up with three names :-)

Will have a look

**Comment by tbates** [comment]
where did you see the name umxMendelianRandomization?

**Comment by lf-araujo** [comment]
Here:

![image](https://user-images.githubusercontent.com/10139950/202251593-397cbde7-6297-4940-81a5-c910d8018ded.png)


https://tbates.github.io/models/1970/09/13/models-IV.html

**Comment by tbates** [comment]
ahh... tutorial out of date... my bad: umxMR used now
