### ISSUE TITLE
mrDOC

### ISSUE THREAD

**Issue by nathangillespie** [tbates/umx#218]
Luis and Tim, In the umxMRDoC.R script [umxMRDoC.R](https://github.com/tbates/umx/blob/master/R/umxMRDoC.R), shouldn't the BE and F matrices include byrow=T? Nathan

**Comment by tbates** [comment]
not sure, as  luis wrote this. Is this not expected?: 

```R
FullMatrix 'BE' 

$labels
     [,1] [,2] [,3]
[1,] NA   "g1" NA  
[2,] "g2" NA   NA  
[3,] "b1" "b2" NA  

$values
     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0

$free
      [,1]  [,2]  [,3]
[1,] FALSE  TRUE FALSE
[2,] FALSE FALSE FALSE
[3,]  TRUE  TRUE FALSE
```

**Comment by nathangillespie** [comment]
I didn’t see that he had included byrow=T at the beginning of the script

On Jun 21, 2023, at 12:06 PM, Tim Bates ***@***.***> wrote:


This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/JqxBPMk!l1OkzxzrvjE7thg0c1XNB3rJn-ZJx1JQ86zgXwVNaEV5YQQi1Lf0CbhkqdQlS0El2dZ8V_6UMYE91wtCW18-swL4Kp8-V9ku-g$>
Report Suspicious


not sure, as luis wrote this. Is this not expected?:

FullMatrix 'BE'

$labels
     [,1] [,2] [,3]
[1,] NA   "g1" NA
[2,] "g2" NA   NA
[3,] "b1" "b2" NA

$values
     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0

$free
      [,1]  [,2]  [,3]
[1,] FALSE  TRUE FALSE
[2,] FALSE FALSE FALSE
[3,]  TRUE  TRUE FALSE

**Comment by tbates** [comment]
The option setting is unsafe in two ways. It's best to set it in each call so it does what the function demands, for these set and forget super functions.

Butt most of all, it is not being reset after the call... that means calling this function alters the behavior of code outside this function... which is bad. 

I've updated the script to be `byRow` explicitly in each `umxMatrix` call

@lf-araujo can you check if i've done the right thing?
t

**Comment by lf-araujo** [comment]
Yes, Tim. These are getting some traction, I have an updated version with the byrow placed as everyone expects.

In BGA, but code is mostly done.

--
T32 | Virginia Institute for Psychiatric and Behavioral Genetics | Richmond | US
Department of Psychiatry | The University of Melbourne | AU
p: +1 804 502-4074  | http://go.unimelb.edu.au/y5yr
________________________________

**Comment by lf-araujo** [comment]
I think this can be closed, @tbates  updated version is more clear. The updated version is coming, but pending paper publication that is taking longer than expected. As happens.

**Comment by tbates** [comment]
PS: `umxMRDoC` is in CRAN version of umx now!
