### ISSUE TITLE
Improve inline-output of umxComparison by adding  delta AIC (already has AIC)

### ISSUE THREAD

**Issue by tbates** [tbates/umx#23]
Just work out AIC new - AIC old, and add it as delta AIC in inline umxComparison

**Comment by tbates** [comment]
proposal would add a new column Delta AIC
```R
m1 = umxRAM("tim", data = mtcars,
	umxPath(c("wt", "disp"), to = "mpg"),
	umxPath("wt", with = "disp"),
	umxPath(v.m. = c("wt", "disp", "mpg"))
)
umxCompare(m1, m1)
```
|Model | EP|∆ -2LL |∆ df |p  |      AIC|Compare with Model |
|:-----|--:|:------|:----|:--|--------:|:------------------|
|tim   |  9|       |     |   | 419.1183|                   |
|tim   |  9|0      |0    |   | 419.1183|tim                |

**Comment by mcneale** [comment]
Seems reasonable.

**Comment by tbates** [comment]
```R
require("umx")
 data(demoOneFactor)
 manifests = names(demoOneFactor)
 m1 = umxRAM("One Factor", data = demoOneFactor, type="cov",
 	umxPath("G", to = manifests),
 	umxPath(var = manifests),
 	umxPath(var = "G"  , fixedAt= 1)
 )

m2 = umxModify(m1, "G_to_x1", name = "no_effect_of_g_on_X5", comparison = TRUE)

umxCompare(m1, m2, report= "inline")
```

> The hypothesis that 'no_effect_of_g_on_X5' was tested by dropping no_effect_of_g_on_X5 from 'One Factor'. This caused a significant loss of fit (χ²(1) = 750.42, p = < 0.001: AIC = 745.81 change in AIC = 748.417).


|Model                | EP|Δ -2LL     |Δ df |p       |        AIC|    Δ AIC|Compare with Model |
|:--------------------|--:|:----------|:----|:-------|----------:|--------:|:------------------|
|One Factor           | 10|           |     |        |  -2.606207|   0.0000|                   |
|no_effect_of_g_on_X5 |  9|750.416577 |1    |< 0.001 | 745.810370| 748.4166|One Factor         |
