### ISSUE TITLE
Allow individual dzCr settings in multivariate umxACE()

### ISSUE THREAD

**Issue by marco-deppe** [tbates/umx#233]
Might be more of a question than an issue - excuse me if this is the wrong place for this, not entirely sure how this works!

In a multivariate `umxACE()`, one might consider some variables that, according to their MZ/DZ correlations, would require _D_, and some variables that would require _C_ to be estimated in order to show the 'full' picture (and improve fit). Is it possible to set individual `dzCr` (e.g., 0, .25, or 1) for different variables?

If not, would it be possible to implement this? E.g., allow `dzCr = c(.25, .25, 1, 1, .25, .25)`, corresponding to the variable list provided? If I am not mistaken, `dzCr` currently only allows a specification for the entire model, not for single variables. 

Any pointers to existing options to achieve this are much appreciated.

**Comment by tbates** [comment]
The trouble with this, though, is that in multivariate models, allowing some traits to have D but not C creates a problem: with only one or the other, trait covariance can be explained. But if one has D and the other C, that can't happen. So in practice, if there really is both D and C, people let A soak up the D, and model C using C.

FYI, umxACE re-uses the C matrix for D in D models, so coping with ACDE would be additional work.
