### ISSUE TITLE
string syntax for umxRAM

### ISSUE THREAD

**Issue by tbates** [tbates/umx#24]
Current slowness in prototyping is the typing out of long variable names, and the visual interference of commas and = signs in umxPath commands.

Graphviz has nice feature of allowing short names. We could do this if, for instance the user provided manifests, we could then let them refer to these as simply m1, m2 etc in path statements.
This might make umxPath calls easy enough, that string input is not worth the hassle.

If we have string input, it should include equate in string
1. a1 == a2
2. a1 + a2 + a3 == 3

    umxRAM("play", manifests = c("extraversion", "neuroticism", "conscientiousness", "depression"),
        sem = "v2*v3->v4"
    )

**Comment by tbates** [comment]
One option is to create `umx_lavaan2RAM()` and let people use that. Trouble is lavaan, like mplus, has defaults, so that code would involve more than just translating what the user requested, but also what lavaan decided their request implied (like variances for manifests etc. I've always avoided that  it only seems smart for about a day...

I am thinking now that the syntax I most like playing with is graphviz, paradoxically also invented at AT&T by the guys who did `R`.

It's very `sem` like, so just:

    A -> B

Which obviates typing all the functions, parameter names, commas and = signs and closing brackets and trailing commas that frustrate people

A nice thing might be to allow abbreviation lists, so that for instance instead of typing:

    umxRAM(paths = "
        Stress <-> Extraversion,
        Extraversion -> Depression
        Stress -> Depression"
    )

One could say

    umxRAM(vars = c(S = Stress, E = "Extraversion", D = "Depression), paths = "
        S <-> E,
        S E -> D"
    )


Both are probably easier than:

    umxRAM("myModel",
        umxPath("Stress", with = "Extraversion"),
        umxPath(c("Stress", "Extraversion"), to = "Depression")
    )

Which in turn beats

    mxModel("myModel", type = "RAM",
       manifests = c("Stress", "Extraversion", "Depression") 
        mxPath("Stress", to = "Extraversion", arrows= 2),
        mxPath(c("Stress", "Extraversion"), to = "Depression")
    )

**Comment by bwiernik** [comment]
I agree that either graphviz or `sem` has the most intuitive syntax. `sem` exactly would be convenient to make it maximally easy to re-use scripts in umx. A reasonable compromise would be to throw a warning if a string syntax model is fit without latent/manifest variances, etc. 

Functions for `umx_lavaan2RAM`, `umx_lavaan2RAM`, and `umx_lavaan2RAM` would be really nice for adapting published scripts. These could perhaps return lists of umx paths. They should include the automatic paths assumed by the various programs, with warnings that they were added. Positioning these functions as conversion tools, not recommended for building one’s own models, would be good.

**Comment by tbates** [comment]
Decided to treat the lavaan syntax as a universal grammar for SEM, and add ability to process this in `umx` via `umxRAM`

**Comment by mcneale** [comment]
Good plan!

**Comment by tbates** [comment]
I'm converting `lavaan` into a mix of `umx` or `OpenMx` calls as is easiest. It all just comes back as an `MxRAMModel` with sub models if it's multi-group, so essentially OpenMx
