### ISSUE TITLE
plot.MxModel  show definition variables (dummy latents) as diamonds

### ISSUE THREAD

**Issue by tbates** [tbates/umx#245]
Would this RAM model be best plotted with the groupID as a diamond labelled "groupID" instead of a circle labelled "def_groupID" ? (from #242)

```R
m1 = umxRAM("Def Means Path Spec", data = df, 
	umxPath(v.m. = c("x","y")),
	umxPath("x", with = "y"),
	umxPath(defn="groupID"), # creates a unit latent called "def_groupID" with data "data.groupID"
	umxPath("def_groupID", to = c("x", "y"))
)
plot(m1)

```

<img width="262" alt="image" src="https://github.com/tbates/umx/assets/736156/bafa202c-83c8-4deb-b5d1-a0bc25e6d4c7">

**Comment by mcneale** [comment]
No.  The definition variable belongs on a path, not a square, not a circle, not a triangle.  I do not like defvars on variables, no sir.  The revised spec with group in a square is quite wrong (no variance of groupid, etc).  What should be shown on the figure is data.defvar as a label for the path from one to def_groupID.  That would denote that i) it's a definition variable, and ii) it isn't necessarily the same value for everyone in the sample.  The labeling of the circle doesn't change the model specification, so it's not very helpful IMO.

**Comment by tbates** [comment]
not needed
