### ISSUE TITLE
umxReduceACE: umx_set_auto_run(autoRun = FALSE); is it correct?

### ISSUE THREAD

**Issue by rogercompte** [tbates/umx#249]
Hello, 

Firstly thanks for the umx package. I am not very proficient in R but needed to easily run ACE models. 
However, the _umxReduceACE_ function was not working.
I got it to run successfuly if I changed _autoRun_ argument from the _umx_set_auto_run_ function to **TRUE**.
Also for the function Weights to work I had to initialise the _MuMIn_ library.
I hope that helps and it is not a mistake. 

Best wishes,

Roger

**Comment by rogercompte** [comment]
Hi @tbates ,

I freshly re-installed everything, se here are the versions I am currently using:
umx version: 4.20.0
OpenMx version: 2.21.13 [GIT v2.21.13]
R version: R version 4.4.1 (2024-06-14 ucrt)

Thank you.

**Comment by tbates** [comment]
This was reported in #241 

Should be fixed now you have the latest umx?

**Comment by tbates** [comment]
closing as fixed. reopen if problem  can be replicated in current version
