### ISSUE TITLE
Add umxSuperModel for easy multi group

### ISSUE THREAD

**Issue by tbates** [tbates/umx#27]
it should be trivial to put models in a super model. just

    m3 = umxSupermodel(name, model1, model2, modeln)

**Comment by tbates** [comment]
Added now: this will make multi-group more straight forward

**Comment by tbates** [comment]
umxSuperModel

**Comment by mcneale** [comment]
Cute function!

On Sep 26, 2017, at 5:23 AM, Tim Bates <notifications@github.com<mailto:notifications@github.com>> wrote:


umxSuperModel
