### ISSUE TITLE
enhance umxACE to output confidence intervals in tables

### ISSUE THREAD

**Issue by tbates** [tbates/umx#33]
currently confidence intervals are a but crufty. They just appear as a list after the nice a, c, e table.

Be good to output a nicely formatted table 

|Phenotype   |   a1|   c1|   e1|
|:--|----:|----:|----:|
|IQ | 72 [.54,.89]| 58 [.21,.64]| 37 [.20,.43]|

**Comment by mcneale** [comment]
Yep, I recommend ; not , for CIs because , is decimal point to some nationalities.

**Comment by tbates** [comment]
smart, ok, so

     .5 [12; 54]

or maybe a set-able option

**Comment by tbates** [comment]
implemented in `1.9.0`!

**Comment by mcneale** [comment]
Sweet!!!
