### ISSUE TITLE
umxACE: enhance plot to include confidence intervals on paths

### ISSUE THREAD

**Issue by tbates** [tbates/umx#34]
self descriptive. won't look good with multivariate, but helpful for univariate to see these on plot

**Comment by mcneale** [comment]
Let's use ; for CIs here too!

**Comment by tbates** [comment]
ok, so eitehr ; or set-able

     .5 [12; 54]

**Comment by tbates** [comment]
plots now have CIs on them! (haven't yet made the switch to euro friendly semi-colons - will implement as a setting.
