### ISSUE TITLE
Add df adjustments to umxSummary, other functions

### ISSUE THREAD

**Issue by bwiernik** [tbates/umx#36]
A common practice in personality SEM analyses is to first estimate a measurement model, then fix these parameters before estimating a path model. With this procedure, the fit statistics for the final model are computed using an incorrect DF parameter--they need to be adjusted downward by the number of fixed parameters that were freely estimated in the measurement model. Currently, I've been doing these adjustments by hand--would it be possible to add a df.adjust parameter to umxSummary and other functions to streamline this process?

**Comment by tbates** [comment]
OK, a sort of 2-stage approach. But you want to manually track and add back in the parameters which were fixed for stability, but which should still be counted as having been computed. OK - I'll look into.

**Comment by bwiernik** [comment]
Thanks! An example of a paper using such an approach:
http://onlinelibrary.wiley.com/doi/10.1002/per.1975/abstract

**Comment by mcneale** [comment]
Without reading the paper (sorry v busy) I figure that this approach biases the standard errors of the parameters in the second-stage model towards being narrower than they should be.  It's not clear to me whether the df.adjust is the right approach to adjusting measures of model fit - have there been simulation studies of the method?

**Comment by tbates** [comment]
`summary.MxModel` has a number of options for controlling numbers of obs, stats etc (list below)

What should the proposed `df.adjust` do, in terms of providing information to `summary.Mxmodel`?

Just get `numStats` and apply `df.adjust` to it?

Would need to specify, also, how to handle these correctly in the computed saturated and independence models...

1. numObs
2. numStats
3. refModels
4. SaturatedLikelihood
5. SaturatedDoF
6. IndependenceLikelihood
7. IndependenceDoF

**Comment by bwiernik** [comment]
Yes, I think that just applying `df.adjust` to `numStats` would be sufficient.
