### ISSUE TITLE
Add umxACEv (variance components version of ACE model)

### ISSUE THREAD

**Issue by tbates** [tbates/umx#38]
Will need
- [x]  new `umxACEv` function
  * what bounds etc. will help make this function stay sane?
- [x]  new `umxSummary.ACEv` S3 method
- [x]  new `plot.ACEv` S3 method
- [ ]  support 'umxReduce'

Should we include support for reporting path coefficients? (or just big ACE?)

**Comment by mcneale** [comment]
Simulation studies to date suggest that this approach stays more sane than the Cholesky(!) That is, it has fewer code reds and stuff.

Most folks want to see quantities like A/(A+C+E) which is fine.  Sometimes might turn out to be negative.  Diagnostics might be provided (especially if SE's are available) to indicate whether, e.g., variance components are < 0, or |r| > 1.  Things will look just as funny for some A/(A+C+E) quantities too - negative heritabilities, and the sum of the **absolute** values of the variance "proportions" can end up being other than 1 - same problem that we already have with genetic correlations.

**Comment by tbates** [comment]
So, have a running version of `umxACEv` (for variance components approach). WIth no lower tri a, c, e matrices.

For BMI, the old output was as below, and `.86^2 +.51^2 =  1`

|     |   a1|c1 |   e1|
|:----|----:|:--|----:|
|bmi1 | 0.86|.  | 0.51|

The new output totals 0.898:

|     |   A1|C1 |   E1|
|:----|----:|:--|----:|
|bmi1 | 0.66|.  | 0.23|

How to explain the missing .1?  Or have I made an error with this code?

		Vtot = A + C + E;         # Total variance
		I  <- diag(nVar);         # nVar Identity matrix
		# Standardized _variance_ coefficients ready to be stacked together
		A_std <- Vtot %*% A; # Standardized variance coefficients
		C_std <- Vtot %*% C;
		E_std <- Vtot %*% E;


PS: This will be quite a bit of work, as all the model, summary, and plot code plus all the helper functions like umx_standardize_ACE  that worked with path matrices has to be re-written to use ACE.

**Comment by mcneale** [comment]
Error in code.  Should be A_std <-  (I/Vtot) %*% A

**Comment by tbates** [comment]
For the ACE variance-component version,  shall we have start values for A, C, and E of
var/3?

PS: The path version has this code, comments welcome :-)

```
# 1. get variance of each variable (for twin 1, close enough for starts)
varStarts = umx_var(mzData[, selDVs[1:nVar], drop = FALSE], format= "diag", ordVar = 1, use = "pair")
				
# 2. setup start values for path matrices (equal across a, c, and e)
if(nVar == 1){
   # sqrt to switch from var to path coefficient scale
   varStarts = sqrt(varStarts)/3
} else {
   varStarts = t(chol(diag(varStarts/3))) # Divide variance by3, and set to Cholesky form.
}
varStarts = matrix(varStarts, nVar, nVar)

```

**Comment by mcneale** [comment]
Yes indeed - about as robust and agnostic as it gets.

**Comment by tbates** [comment]
Done
