### ISSUE TITLE
warn users if data variances are too small

### ISSUE THREAD

**Issue by tbates** [tbates/umx#41]
this version is available on github via
    install_github("tbates/umx")

It runs fine for univariate, but a bivariate example is failing with bad starting values.

The un-run model can be gotten by saying:

    m1 = umxACEv(selDVs = c("ht", "bmi"), dzData = dzData, mzData = mzData, sep="", autoRun = F)

Here's the code to show the failure:

    require(umx); data(twinData)
    mzData <- twinData[twinData$zygosity %in% "MZFF", ]
    dzData <- twinData[twinData$zygosity %in% "DZFF", ]
    
    # 1 var works
    m1 = umxACEv(selDVs =  "ht", dzData = dzData, mzData = mzData, sep="")
    
    # 2, bivariate doesn't get off the ground
    m1 = umxACEv(selDVs = c("ht", "bmi"), dzData = dzData, mzData = mzData, sep="")
    
    1: The continuous part of the model implied covariance (loc2) is not positive definite in data 'DZ.data' row 5. Detail:
    # covariance =  matrix(c(    # 3x3
    #  0.00427128, 0.3, 0.00213564
    # , 0.3, 0.941062, 0.15
    # , 0.00213564, 0.15, 0.00427128), byrow=TRUE, nrow=3, ncol=3)
    #
    # )
    # In addition: Warning message:
    # In model 'ACE' Optimizer returned a non-zero status code 10. Starting values are not feasible. Consider mxTryHard()

**Comment by mcneale** [comment]
This would seem to be a problem:

> coef(m1)
expMean_r1c1 expMean_r1c2       A_r1c1       A_r2c1       A_r2c2       C_r1c1       C_r2c1       C_r2c2       E_r1c1       E_r2c1       E_r2c2 
  1.62259279  21.65292765   0.00142376   0.00000000   0.31368746   0.00142376   0.00000000   0.31368746   0.00142376   0.00000000   0.31368746 

A C and E are all teeny-tiny for r1c1

**Comment by tbates** [comment]
That (`var(mzData$ht2, na.rm=T) #  0.00426`) is the correct variance for height (well, 1/3 of it). Is the issue just small numbers? (the sqrt of this  (0.065) worked fine as a start for `a` in path coefficient version, which comes to the same thing in `a %*% t(a)`).

It's also running fine with just height (univariate). Is the issue that OpenMx stopping when single rows entering non-positive definite space while the model as a whole is correctly tracking in on the solution?

Forcing users to scale their variables when var < k_min would help. Should we check variances and advise scaling? If so, what minimum?

    data(twinData)
    twinData$ht1 = twinData$ht1 *1000 # convert m to mm
    twinData$ht2 = twinData$ht2 *1000
    mzData = twinData[twinData$zygosity %in% c("MZFF", "MZMM"),]
    dzData = twinData[twinData$zygosity %in% c("DZFF", "DZMM", "DZOS"), ]
    m1 = umxACEv(selDVs = c("ht", "wt"), suffix = '', dzData = dzData, mzData = mzData)

**Comment by mcneale** [comment]
It is definitely a bad idea to work with variables with very small variances.  Simply multiply every score by 100 or so and everything should be fine.  This is essentially a corner case.

I'd set a minimum variance of .1 - should do the trick.  What I suspect is going on is that the covariance parameter gets tweaked so that the correlation is >1 - could use Checkpointing to verify that this is what occurs.

**Comment by tbates** [comment]
Will it upset expert users to have the `umxACE` family of functions say something like

> Fitting variables with near-zero variance is prone to failure. It is easily avoided by expressing the variable in smaller units. For instance for height, one might use units of mm instead of meters. You should consider multiplying the following variables by a constant to avoid problems: 
: List of small variances encountered…

**Comment by mcneale** [comment]
Perhaps.  It might be better to do it for them, and then undo it afterwards, automagically... (SE's can be recalculated with mxSE quite effectively I figure).  If we just tell them what we're doing and why, they may go away happy campers.

**Comment by tbates** [comment]
I'll add auto detect + alert and see how that feels.

If we change data, we could mesage the user with which power of 10 was chosen for each variable. Or else offer to auto-z-score everything.

    rescale = c("ask", "z", "power-of-ten", "never")

If we auto-scale but then return the data in their old form, Only umx functions will know to change the data. so the model won't re-run correctly.

Might be too that SE-based intervals in the raw data would suffer the same error?

Note to self: If we go that route:  need to postpone requested profile CIs if requested until back in the "correct" scale.


Food for thought.

**Comment by mcneale** [comment]
Thinking about it, warning is good enough, with recommended scale factor.  We should return in the transformed scale if we transform at the user's request.

**Comment by tbates** [comment]
Hi mike!

Still think var < 0.1 is  a good rule be for warning users about excessively small variances?

Will add this inside to  `xmu_make_mxData`, which will cause it appear in all twin models and umxRAM models.

```R
umx_check_variance(twinData[, c("wt1", "ht1", "wt2", "ht2")], minVar = .1)
```

**Comment by mcneale** [comment]
That seems about right, though this is not empirically tested.  It may be a bit high but better safe than sorry. If variances differ by orders of magnitude it can cause issues with the Hessian, perhaps be on the lookout for such issues and rescale.  For maximum robustness we could rescale everything, but this is problematic with twin data where, e.g., height should be scaled to T1’s variance, NOT separately for T2 - so that df for replicate statistics remain correct.

**Comment by tbates** [comment]
should make this these defaults into options with a get/set function, like `umx_set_data_variance_check()`

And then look up values from there

Changed the default variance ratio check 1000:1

**Comment by tbates** [comment]
`umxRAM` and the twin models now show a polite note when variances are too small or too disparate. The default trigger can be set using `umx_set_data_variance_check`

**Comment by tbates** [comment]
Models now warn user and offer a solution.
> The variance of variable(s) 'ht1' and 'ht2' is < 0.1.
You might want to multiply to express the variable in smaller units, e.g. cm instead of metres (or umx_scale these variables in long-format).

Also created:

```R
# print current criteria
umx_set_data_variance_check()
```
> Current threshold for small variance warning in umx functions is '0.01'
Current threshold for excess ratio among variances warning in umx functions is '500'

And update
```R
umx_set_data_variance_check(minVar=.01, maxVarRatio=500)
```
