### ISSUE TITLE
umxSexLim features and umxSummary()

### ISSUE THREAD

**Issue by tbates** [tbates/umx#43]
hi all,
Correlated Factors multi-variate `umxSexLim()` is taking shape.

`m1 = umxSexLim("sexlim", selDVs, mzmData, dzmData, mzfData, dzfData, dzoData, A_or_C = "A"))`

Any thoughts on how to plot? 

`umxSummary` will return something like below -thoughts?

### Standardized A, C, & E by Sex
|   |  ssc|  sil|  caf|  tri|  bic|
|:--|----:|----:|----:|----:|----:|
|Am | 0.77| 0.73| 0.70| 0.75| 0.67|
|Cm | 0.01| 0.08| 0.15| 0.06| 0.10|
|Em | 0.21| 0.19| 0.15| 0.19| 0.23|
|Af | 0.78| 0.77| 0.43| 0.70| 0.65|
|Cf | 0.02| 0.07| 0.41| 0.11| 0.15|
|Ef | 0.20| 0.16| 0.16| 0.19| 0.20|

Perhaps layout factor correlations f in upper tri, m in lower?

### Factor Correlations

(_note_: Females on lower triangle, Males on upper-triangle)

### A Factor Correlations

|    | sscAm| silAm| cafAm| triAm| bicAm|
|:---|-----:|-----:|-----:|-----:|-----:|
|ssc |  1.00|  0.72|  0.33|  0.56|  0.56|
|sil |  0.67|  1.00|  0.34|  0.59|  0.52|
|caf |  0.27|  0.34|  1.00|  0.55|  0.21|
|tri |  0.52|  0.64|  0.58|  1.00|  0.61|
|bic |  0.57|  0.57|  0.37|  0.65|  1.00|

### C Factor Correlations
|    | sscCm| silCm| cafCm| triCm| bicCm|
|:---|-----:|-----:|-----:|-----:|-----:|
|ssc |  1.00|  0.31|  0.16| -0.11|  0.03|
|sil |  0.31|  1.00|  0.24|  0.17|  0.64|
|caf |  0.16|  0.24|  1.00|  0.35|  0.46|
|tri | -0.11|  0.17|  0.35|  1.00|  0.74|
|bic |  0.03|  0.64|  0.46|  0.74|  1.00|

### E Factor Correlations

|    | sscEm| silEm| cafEm| triEm| bicEm|
|:---|-----:|-----:|-----:|-----:|-----:|
|ssc |  1.00|  0.41|  0.28|  0.41|  0.32|
|sil |  0.55|  1.00|  0.33|  0.41|  0.37|
|caf |  0.33|  0.36|  1.00|  0.37|  0.42|
|tri |  0.37|  0.39|  0.28|  1.00|  0.41|
|bic |  0.37|  0.43|  0.33|  0.46|  1.00|

**Comment by mcneale** [comment]
Summary looks good, although at least optionally including CIs or SEs would be nice.

**Comment by tbates** [comment]
For `umxSexLim`, `umxSummary` needs to include Rao/Rco. Show one column empty, or switch label?


|   am | cm |   em  |  af |   cf     |  ef   |  Rao |  Rco |
|-------:|:-----|-------:|-----:|-------:|------:|-------:| -------:|
| 0.77 |.      | 0.23 | 0.7  | 0.11 | 0.2  | .87    | .        |

Also, would it be better for the eye to put the m and f side by side instead of ace/ace?

|   am | af   |   cm  |  cf     |   em |  ef   |  Rao |  Rco |
|-------:|:-----|-------:|-------:|-------:|------:|-------:| -------:|
| 0.77 |0.70  | 0.0  | 0.11 | 0.23  | 0.20  | .87    | .        |

**Comment by mcneale** [comment]
I would leave one column blank.  Other designs (adoption,  sibs vs half-sibs etc) would be able to estimate both simultaneously.

The other question is more difficult.   I'm somewhat in favor of am af cm cf,  but don't feel strongly.  It  partly depends on what  the main focus of the analysis/results is.  If sex differences then am af is the way to go.  If more interested in the within-sex variance components, then better to use the am cm... format.

**Comment by tbates** [comment]
ok: both Rao and Rco columns added and arranged components as mf mf mf

**Comment by tbates** [comment]
The `devtools::install_github("tbates/umx")` version has a working `umxSexLim` as of today.

Would be helpful to have someone look over the description text in `?umxSexLim` and also to look over all the examples I've included at the bottom of the help file to see I'm doing the right thing. 

Complex, this correlated factors, multi-variate, qual and quant, 5-group model :-)

**Comment by tbates** [comment]
nice to see people using this now
