### ISSUE TITLE
improve umxSummary to support multi group RAM (now that we have umxSupermodel

### ISSUE THREAD

**Issue by tbates** [tbates/umx#45]
`umxSummary` should support multi-group RAM models, built by `umxSupermodel`

**Comment by tbates** [comment]
implemented in 2.0.0; debugged in 2.0.1

**Comment by mcneale** [comment]
Got any pics of umxSupermodel? :)

**Comment by tbates** [comment]
That's a good feature request: plotting sub models... will think if there's a rational way to do it 🥇

**Comment by mcneale** [comment]
In multi group, the models are effectively independent and could be unified in a single diagram.  This is the way onyx does it - treating MZ and DZ in same group as a missing data problem
MZ1 MZ2 DZ1 DZ2
Obviously this is not suitable (independent diagrams) if the MZ and DZ twins are from the same family, although that could be modeled by allowing covariances between the MZ and DZ models.

**Comment by tbates** [comment]
OK, so `plot` would just draw each sub and then to a smart concatenatation of the dot files. Should be doable. I'll open a new issue for plot referencing this issue.
