### ISSUE TITLE
enhance plot to work with super/sub models

### ISSUE THREAD

**Issue by tbates** [tbates/umx#46]
#45 ended with umxSummary outputting nice tables for nested models.

`plot` should be able to just draw each sub as it would on its own, and then do a smart concatenatation of the dot files before drawing/writing them.

Should be doable.

**Comment by mcneale** [comment]
Yes, sounds very nice - and goes a good way towards Open Science principles.

**Comment by tbates** [comment]
something like this might work, but requires unique names... I might just open two plot pages, and let the user switch between them
```
digraph G {
 subgraph cluster_one {
    eggs_1; chicken_1; ham_1;
    label="school1";
    graph[style=dotted];
 }
 subgraph cluster_two {
    eggs_2; chicken_2; ham_2;
    label="school2";
    graph[style=dotted];
 }
}
```

**Comment by tbates** [comment]
Plot now opens a separate browser window/graffle file for each plot of a subgroup of a model, and also all plots are now labeled `"model name> <group name>"`
