### ISSUE TITLE
allow words and bracket addresses in bounds of umxMatrices

### ISSUE THREAD

**Issue by tbates** [tbates/umx#59]
Instead of this sort of thing for ubounds
```R
lbound = c(-1, NA, NA,NA,NA,NA,NA,NA, 1)
```
allow this:

```R
lbound = c("[3,3]"=-1, "[1,1]"=1)
```
and perhaps

```R
lbound = c("diagonal" = 1e-4)
```

**Comment by mcneale** [comment]
Definitely not “instead” - way too commonly used and convenient R code, probably with legacy aplenty. For individual cases in a big matrix, why not 
`BigMat$lbound[1,1] <- -1`
Or
`for (i in 1:n) {BigMat$ubound[i,i] <- 1}`
I don’t see the advantage in going for special-to-this-function syntax - more to learn and get wrong.

**Comment by tbates** [comment]
Good to know. Would not be instead, but as shortcuts. You're likely right - more to learn.

Closing...
