### ISSUE TITLE
umxRAM string syntax multi-group support

### ISSUE THREAD

**Issue by tbates** [tbates/umx#67]
- [x] Add a `group = "column name` parameter to `umxRAM` (will create a group for each level of `group`, returned in a `umxSuperModel` with labels suffixed to distinguish the groups
- [ ] Implement `group.equal` to support equating labels across multiple groups (see below for thoughts on how)
- [ ] Tutorial on using this

**Comment by tbates** [comment]
This would return a 2-group superModel, one group for automatic, one for manual:

```R
m1 = umxRAM("myModel", umxPath(v.m. = "wt"), group = "am", data = mtcars)
```

not sure what the more useful default labels would be: equate paths across groups, or start off free to take distinct values? i.e., `c("wt_with_wt", "wt_with_wt")` or  `c("wt_with_wt_grp1", "wt_with_wt_grp2")`

**Comment by mcneale** [comment]
v.m. is much too cryptic for my taste.  Almost as bad as LISREL :(.  

Anyway, why not make the choice under user control: equateGroups=F or T?

**Comment by tbates** [comment]
yeah, just wondering if equateGroups=FALSE should be the default. Will do that.
To set what is equated, Lavaan allows a list of none or more of c("loadings", "intercepts", "means", "regressions", "residuals", "covariances") which is a decent norm to follow.

re cryptic: nothing's as cryptic as LISREL :-) Avoided now. Suggestions welcome as always.

**Comment by mcneale** [comment]
Nothing like developing something everyone needs scads of training to be able to use, in order to set up a market for lucrative workshops...

**Comment by khusmann** [comment]
Just some thoughts on this interface -- if everything starts free to have distinct values (i.e. `c("wt_with_wt_grp1", "wt_with_wt_grp2")`) then it's easy to go back and whatever things you want to be equal with umxModify and some regex. In fact, a umxModifyGroup helper could make it even more seamless for common workflows.

**Comment by tbates** [comment]
@khusmann That's feels like a 'umx' approach. I think labels default to distinct values now. So job done :-)

I'll think through the `umxModifyGroup` helper idea. It probably could just be `umxModify` with an `equateGroup` parameter to auto-generate regular expressions to handle common group/measurement invariance tasks.

Thanks for your pull request and interest!

**Comment by khusmann** [comment]
> I think labels default to distinct values now. So job done :-)

Actually, I think it defaults to them being all equal? But should be easy to change.

> It probably could just be umxModify with an equateGroup parameter to auto-generate regular expressions to handle common group/measurement invariance tasks.

Something like that sounds good!

**Comment by mcneale** [comment]
This should work generally in cases where the models are identical except for parameter labels.  Some other cases where parameters are all consistently labeled with _grp1 or _grp2 - even if they aren't in the same matrix elements in the two groups would also be useful.  For example, MZ and DZ models often differ structurally, although many parameters are often equated across the two.  Could provide quick tests of, e.g., equality of means & variances.

**Comment by tbates** [comment]
You're right @khusmann, `umxRAM` leaves groups fully equated: It was easy to copy the base model,, appending the group to the model name, and swapping in the correct set of data rows.

It's beta functionality, with `group.equal` not implemented as yet, so I'll change the default to independent.

I don't tend to build things this way (it all got a bit automagical, so I tend to stick to building each model, and place in a `umxSuperModel` myself, so completing this hasn't been a priority). Still... worth getting right.

For post-modification the  `wt_with_wt_grp1`  style default makes manipulation by label easier. So I'll implement that

**Comment by tbates** [comment]
For an architecture to equate things in groups, is it better IYHO, to use the lingua-Lavaanica, adding controls for:
> c("loadings", "intercepts", "means", "regressions", "residuals", "covariances")

(and are there definitions somewhere of these somewhere, unclear what they mean)

Or go with more straightforward explicit terms:
* factor_means
* factor_covariances
* factor_to_observeds
* residual_means
* residual_variances

h/t @mcneale

**Comment by tbates** [comment]
OK: Default is now independent groups. 
Have a play:  `install_github("tbates/umx")`


```R
mtcars$litres = mtcars$disp/61.02
m1 = umxRAM("tim", data = mtcars, group = "am",
  umxPath(c("wt", "litres"), to = "mpg"),
  umxPath("wt", with = "litres"),
  umxPath(v.m. = c("wt", "litres", "mpg"))
)
```

|name                 | Estimate|    SE|
|:--------------------|--------:|-----:|
|wt_to_mpg_1          |   -6.946| 1.950|
|litres_to_mpg_1      |   -1.111| 0.842|
|mpg_with_mpg_1       |    5.382| 2.111|
|wt_with_wt_1         |    0.351| 0.138|
|litres_with_wt_1     |    0.676| 0.293|
|litres_with_litres_1 |    1.885| 0.739|
|one_to_mpg_1         |   43.753| 3.313|
|one_to_wt_1          |    2.411| 0.164|
|one_to_litres_1      |    2.352| 0.381|
|wt_to_mpg_0          |   -1.775| 1.131|
|litres_to_mpg_0      |   -1.057| 0.487|
|mpg_with_mpg_0       |    4.583| 1.487|
|wt_with_wt_0         |    0.573| 0.186|
|litres_with_wt_0     |    1.089| 0.394|
|litres_with_litres_0 |    3.088| 1.002|
|one_to_mpg_0         |   28.868| 2.757|
|one_to_wt_0          |    3.769| 0.174|
|one_to_litres_0      |    4.759| 0.403|

χ²(0) = 0, p = 1.000; CFI = 1; TLI = 1; RMSEA = 0

**Comment by mcneale** [comment]
> For an architecture to equate things in groups, is it better IYHO, to use the lingua-Lavaanica, adding controls for:
> 
> > c("loadings", "intercepts", "means", "regressions", "residuals", "covariances")
> 
> (and are there definitions somewhere of these somewhere, unclear what they mean)
> 
> Or go with more straightforward explicit terms:
> 
> * factor_means
> * factor_covariances
> * factor_to_observeds
> * residual_means
> * residual_variances
> 
> h/t @mcneale

IMO, we should try to avoid new, coded, language constructs if natural language ones suffice.  If, however, there is a big pool of Lavaanicans out there, we (er, you) could probably offer BOTH approaches.  Let the most intuitive one win :).

**Comment by tbates** [comment]
Is this the dictionary of synonyms?

|     natural language                  | lavaanican  |
|:--------------------|:------------|
| factor_to_manifest       | loadings       |
| causal_paths                | regressions  |
| factor_covariances      | covariances |
| manifest_covariances | covariances |
| factor_means           | intercepts    |
| factor_variances     | ???                |
| residual_means       | means          |
| residual_variances  | residuals      |

**Comment by mcneale** [comment]
I guess so, yes.  Factor variances and covariances might be integrated (they are the same when there’s only one factor) but one could see users being interested in whether factors covary the same amount in different groups.   I am thinking that SD %&% R might be a useful specification, separating a diagonal matrix of SDs and a symmetric correlation matrix of factor correlations.  This would enable detecting different factor correlations even if their variances differ.

Residual means and variances are interesting.  Note that the two are confounded with binary data!  Another thing is that I think causal paths are ambiguous.  Factor to manifest are causal paths, but I suspect what is being distinguished here is stuff that happens at the latent to latent level - one factor causes another etc.  So I would replace causal_paths with latent_causal_paths or just latent_causal.   In principle, one could have manifest_causal if observed variables are allowed to cause each other - somewhat network-style.

It’s nice to be able air things like this online - a pity we don’t get more input from the user base though.

**Comment by tbates** [comment]
I'm thinking "_what will I actually use this for_" and apart from "_not much_" :-) I'm thinking 1. measurement invariance and 2. model updating.

From the model updating perspective, the user will nearly always want to make custom changes and these words will be ambiguous and better specified as lists of paths or regular expressions. 

From the measurement invariance approach, when implemented, this will likely bury everything under an umbrella `umxMeasurementInvariance()` helper and so this interface isn't needed.

I think having granted the @khusmann's wish of groups defaulting to independent, I'm going to put this on the back burner for a while. 

Re: feedback: the latent mixture distribution is users (request help) and developers (suggest improvements) :-)

**Comment by mcneale** [comment]
Can you elaborate on the feedback?  For latent mixture distribution, I recommend starting with my nonnor() function, which has options for integrating over the latent trait distributions.

Agreed, umxMeasurementInvariance will simplify things a lot.  It may still be useful to have these classes of equality easily accessible.

**Comment by khusmann** [comment]
> OK: Default is now independent groups.
> Have a play:

Cool! I'm still deciding if I think this is a bug or feature but looks like I can also make things equal across groups by adding a label:

```
mtcars$litres = mtcars$disp/61.02
m1 = umxRAM("tim", data = mtcars, group = "am",
            umxPath(c("wt", "litres"), to = "mpg"),
            umxPath("wt", with = "litres", labels = "lab"),
            umxPath(v.m. = c("wt", "litres", "mpg"))
)
```

Speaking as a user, I think I would have expected added labels to also receive _grp? Otherwise there's no way for me to make custom label names different across groups unless I make a model without label names then change them with regex.

> From the model updating perspective, the user will nearly always want to make custom changes and these words will be ambiguous and better specified as lists of paths or regular expressions.

I'm a newbie but yeah, this is generally the camp I fall in. The lavaan type equality constraints are a bit automagical and seem only useful if I'm fitting simple models. (otherwise I'd worry about the assumptions it was making).

I like the idea of having the group.equality for compatibility with lavaan-types, but having a different workflow for umx-ers around lists of paths or regex.

I've also recently moved away from the group= and am instead doing a pattern like this:

```
build_submodel <- function(groupName, autoRun = F) {
  umxRAM(paste0("submod_", groupName),
    data = mtcars[mtcars$am==groupName, ], autoRun = autoRun, suffix=paste0('_', groupName),
    umxPath(c("wt", "litres"), to = "mpg"),
    umxPath("wt", with = "litres"),
    umxPath(v.m. = c("wt", "litres", "mpg"))   
  ) 
}

mtcars$litres = mtcars$disp/61.02
m1 = umxSuperModel("kyle", lapply(unique(mtcars$am), build_submodel))
```

That way I can also easily run one of the submodels all by itself if I want:

```
m1_1 = build_submodel(groupName=1, autoRun=T)
```

Just a little window into how I'm thinking about things / using them right now. It's not far off the current group= implementation, but allows me to put custom labels that can be different across groups pretty easily. I think if suffix'es were attached to custom labels, I would probably just go back to the group= syntax, but I'm still figuring out how much flexibility in my submodels I actually need.

**Comment by tbates** [comment]
re: label in umxPath being left untouched: Yes, `umx` leaves user labels alone, so I think it's as you say a feature that might be an irritant if you want to build multi-group models *and* you over-ride the built-in automatic labels.

the work-around here is easy: don't add custom labels in the model build, then if you really really want non-standard labels, just replace the built in `a_to_b` with `beta1` or whatever, and that will all still work with group suffixes.

**Comment by tbates** [comment]
Thanks for sharing your workflow and intuitions!

I'l get around to adding `group.equality` if only for compatibility.

re your group function. Nice use of lapply! I'll cogitate on finding user-labels and suffixing them... It makes sense when one knows the user has set `group =` ...  On the other hand, using custom labels to except them from group suffixing is a nice explicit way to equate a handful of paths.

Nearly everything lavaan does is great for simple work and can become a headache for more complex cases, and I think that's what we're seeing here with the group= extension in `umxRAM`: It was designed just to handle that simple teaching/playing around case of using a column to create groups from a dataset in one easy function.

Thanks again!
t

**Comment by khusmann** [comment]
> It makes sense when one knows the user has set group = ... On the other hand, using custom labels to except them from group suffixing is a nice explicit way to equate a handful of paths.

Maybe, for consistency, have suffixes apply universally, including with custom labels. So

```
umxRAM("kyle",
    data = mtcars, suffix="_mysuffix",
    umxPath(c("wt", "litres"), to = "mpg"),
    umxPath("wt", with = "litres", labels="lab"),
    umxPath(v.m. = c("wt", "litres", "mpg"))   
  ) 
```

Would create a lab_mysuffix instead of just lab. Then for groups:

```
umxRAM("kyle",
    data = mtcars, group="am",
    umxPath(c("wt", "litres"), to = "mpg"),
    umxPath("wt", with = "litres", labels="lab"),
    umxPath(v.m. = c("wt", "litres", "mpg"))   
  ) 
```

I'd get lab_1 and lab_0. If I wanted to set those equal, I'd do a regex umxModify to set lab_\d to just lab. It's easier to go this direction rather than starting with lab equal across groups and then trying to umxModify them to be different later.

Similarly, if I use group AND suffix:

```
umxRAM("kyle",
    data = mtcars, group="am", suffix="_mysuffix"
    umxPath(c("wt", "litres"), to = "mpg"),
    umxPath("wt", with = "litres", labels="lab"),
    umxPath(v.m. = c("wt", "litres", "mpg"))   
  ) 
```

I'd expect lab_1_mysuffix and lab_0_mysuffix.

Just some thoughts! Definitely worth cogitating on, I realize these sort of decisions can sometimes have surprising edge cases.

**Comment by tbates** [comment]
Hi @khusmann,

Currently, when the user specs a label in a `umxPath`, they are expecting to override any other command.

So I'm guessing that re-writing the user's "lab" as "lab_mysuffix" would create more hassles than it would solve. (esp when the user taking the time to write `lab` can so easily and directly write `lab_mysuffix`).

Basically, the system is designed to have auto-create universally-rational labels of the form `"a_kind_b"` that can be automated, but still allow the edge case of users wanting to inject arbitrary labels if they want/need/expect to.

So, I think I'll leave this as is for now, given the side effects.

**Comment by khusmann** [comment]
Ah, that makes sense! Thanks for the reply.
