### ISSUE TITLE
umx_make_TwinData: return a data.frame like `twinData`

### ISSUE THREAD

**Issue by tbates** [tbates/umx#76]
`umx_make_TwinData` simulates a range of twin data, but returns it as a list, with an element for each group e.g. `MZ = tmp[[1]]; DZ = tmp[[2]]; `

Changing this to return a dataframe with a "zygosity" column would more comprehensible for most users, extensible to more groups, and more compatible with functions like `umx_scale_wide_twin_data` and `umx_wide2long ` as well as substituting for things like the built-in `twinData` dataset.

**Comment by tbates** [comment]
done

```R
umx_make_TwinData(nMZpairs=10,AA=.5,CC=.1)
 AA  CC  EE 
0.5 0.1 0.4 
   a    c    e 
0.71 0.32 0.63 
        var_T1      var_T2 zygosity
1   1.32053110  0.76710177       MZ
2  -0.99056640 -1.00154408       MZ
3  -0.28957044 -0.06915342       MZ
4  -0.49291505 -1.22230494       MZ
5  -0.26267426  0.83027193       MZ
6   1.34825421  1.31576620       MZ
7  -0.35551471 -0.64246170       MZ
8   0.66447306  0.84947928       MZ
9  -0.65181542  0.13394285       MZ
10 -0.64801075 -0.48879453       MZ
11  0.32903340  0.69374038       DZ
12  0.05722165 -0.19389418       DZ
13 -0.84618259  0.14509410       DZ
14  1.46440488  0.16139762       DZ
15 -0.06369834 -1.58570284       DZ
16  0.21818823 -0.96001652       DZ
17  0.53741235 -0.52969754       DZ
18  1.82211688  1.53419106       DZ
19 -1.31429205 -1.65793722       DZ
20  1.17270461 -0.25083466       DZ

```

**Comment by mcneale** [comment]
Does it permit negative variance components as long as sum of the 3 is positive?  This would allow ADE to be simulated.

**Comment by tbates** [comment]
You can do this:
```R
tmp = umx_make_TwinData(100, MZr = .7, DZr = .20, varNames = "IQ")
m1 = umxACE(dzCr=.25, selDVs="IQ", dzData=subset(tmp, zygosity=="DZ"), mzData=subset(tmp, zygosity=="MZ"), sep="_T")

```
|   |   a1|   d1|   e1|
|:--|----:|----:|----:|
|IQ | 0.54| 0.69| 0.48|

But the variance components interface currently doesn't allow negative values:
```R
umx_make_TwinData(nMZpairs=10,AA=.5,CC=-.2)
```
> Error: Hmm, each of the AA, CC, and EE variance components must be positive, but  CC  was negative.

Shall I add a double D  parameter (seems more straightforward than negative C?), in the first instance, would simulate ADE instead of ACE data if `!is.null(DD)`. Could extend to support ACDE.

**Comment by mcneale** [comment]
Another possibility would be to allow for DD directly.  Yet another would be sibling interaction but that is less widely used.
