### ISSUE TITLE
umx_make_TwinData: support DD (non-additive component)

### ISSUE THREAD

**Issue by tbates** [tbates/umx#78]
Allow this:
```R
tmp = umx_make_TwinData(AA= .4, DD= .4, C=0)
m1 = umxACE(selDVs="var", dzCr=.25, data = tmp)

```
|   |   a1|   d1|   e1|
|:--|----:|----:|----:|
|var | 0.4| 0.4| 0.2|

_Originally posted by @tbates in https://github.com/tbates/umx/issues/76#issuecomment-507241329_

**Comment by tbates** [comment]
Done: Example simulating both D & C > 0

```R
tmp = umx_make_TwinData(nMZ = 1000, AA = .4, DD = .2, CC = .2)
```
| | AA | CC | DD  | EE |
|:---|----:|----:|----:|----:|
| var     |0.4  | 0.2 | 0.2 | 0.2 |
| path     | .63 | .45 | .45 | .45 |

Then running ACE and ADE on the resulting data: makes a nice tutorial

```R
m1 = umxACE(selDVs="var", data = tmp)
```
ACE

|    |   a1|   c1|   e1|
|:---|----:|----:|----:|
|var | 0.86| 0.24| 0.45|
```R
m1 = umxACE(selDVs="var", data = tmp, dzCr=.25)
```
ADE

|    |  a1|d1 |   e1|
|:---|---:|:--|----:|
|var | 0.9|.  | 0.44|

**Comment by mcneale** [comment]
Interesting.  Without additional relative types there’s an identification problem.   Makes me wonder: might they be readily output too, given A/C/D covariance coefficients?  The wrench in the works, as always is assortative mating.

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 Richmond VA 23298-0126
Telephone: (804) 828-3369

On Jul 2, 2019, at 2:37 PM, Tim Bates <notifications@github.com<mailto:notifications@github.com>> wrote:


Done: Example simulating both D & C > 0

tmp = umx_make_TwinData(nMZ = 1000, AA = .4, DD = .2, CC = .2)

AA      CC      DD      EE
var     0.4     0.2     0.2     0.2
path    .63     .45     .45     .45

Then running ACE and ADE on the resulting data: makes a nice tutorial

m1 = umxACE(selDVs="var", data = tmp)

ACE

a1      c1      e1
var     0.86    0.24    0.45

m1 = umxACE(selDVs="var", data = tmp, dzCr=.25)

ADE

a1      d1      e1
var     0.9     .       0.44

**Comment by tbates** [comment]
Could add option to deviate rA from .5 pretty easily, and allow simulating data from a trait with assortative mating.

You mean output the other relatives? That's a nice idea. What would be most useful? Probably will be a back burner project, as we don't yet have umx functions for extended twin design, but a teaching toy would be easy to mock up.

No identification problem on the data generation side, of course :-) I just:

```R
ACDE  , hA+C+qD
hACqD,           ACDE
```
