### ISSUE TITLE
[minor] Allow "sep" as a synonym for "suffix" in twin models

### ISSUE THREAD

**Issue by tbates** [tbates/umx#8]
The separator in twin variable names (e.g. the `"_T" ` in `var1_T1` is called `suffix` in umxACE, umxCP, umxIP etc. Might aid consistency and R expectations if `sep` was allowed?

e.g. 
`
m1 = umxCP(selDVs = genItems, dzData = dzData, mzData = mzData, sep = "_T")  # proposed
m1 = umxCP(selDVs = genItems, dzData = dzData, mzData = mzData, suffix = "_T") # existing
`

**Comment by mcneale** [comment]
Allowed when and where and to do what?

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 Richmond VA 23298-0126
Telephone: (804) 828-3369  michael.neale@vcuhealth.org<mailto:michael.neale@vcuhealth.org>

On Jan 23, 2017, at 9:40 AM, Tim Bates <notifications@github.com<mailto:notifications@github.com>> wrote:


the "_T" separator in names like "var1_T1" is called "suffix". Might aid R users if "sep" was allowed?

**Comment by tbates** [comment]
users can now form twin variable names from a base name by specifying `sep="_T"` OR `suffix = "_T"` to help learning in expert R users who reflexively use "sep" to concatenate strings.
Works in umxACE, umxCP, umxIP
