### ISSUE TITLE
tmx_show: make smarter and more graphical

### ISSUE THREAD

**Issue by tbates** [tbates/umx#80]
Easy initial task: allow it to show multiple groups contained in a RAM supermodel

```R
tmx_show(m1)
Error in tmx_show(m1) : 
  I can only show the components of RAM models: You gave me an MxModel
```
Second, while `tmx_show` currently has nice defaults for models (below), it might be nice to have a slick model overview in a web page, with muted background cell color to show fixed or free (red or green), and a toggle on the web page to show  labels, values, or both in each cell. Perhaps display a graphical plot() in a second column on the same page.

```R
tmx_show(m1$play_1)
```

Values of S matrix (0 shown as .):

|    |   mpg|    wt|
|:---|-----:|-----:|
|mpg | 35.19| -4.96|
|wt  | -4.96|  0.93|

Values of A matrix (0 shown as .):

|    |mpg |wt |
|:---|:---|:--|
|mpg |.   |.  |
|wt  |.   |.  |

Values of M matrix (0 shown as .):

|   mpg|   wt|
|-----:|----:|
| 20.09| 3.22|
>

**Comment by mcneale** [comment]
About 6% of males are red green color blind... how about red blue?

**Comment by tbates** [comment]
Now has a web view for matrices with gray color for fixed parameters, mouse over to see labels.

Also supports show/suppressing path@0 for clarity, digits, choice of table styles 

e.g. S matrix for the front-page model (roll-over not dynamic in this snapshot image):

<img width="584" alt="tmx_show graph! 2020-10-18 at 15 36 26" src="https://user-images.githubusercontent.com/736156/96386151-b1bf5000-1190-11eb-8206-7166f61baba4.png">
