### ISSUE TITLE
v.m. too cryptic?

### ISSUE THREAD

**Issue by tbates** [tbates/umx#99]
Hi #1 user :-) The goal is less typing (1-liner to create free var and mean) while retaining clarity.

If `v.m.` fails, any thoughts for better synonym?

Trouble with "plain english" is that even "freeVarianceAndMean" is obscure to the person who thinks "MeansAndVarsFree". Might be no shortcut to some learning curve. And clarity seekers best to use the non-cryptic

```R
umxPath(var = "bob")
umxPath(mean = "bob")
```

The only other thought I have is two new functions?
```R
manifestVars("bob") # with default smart-starts for mean and variance
latentVars("jane") # with defaults varFixedAt = 1, meanFixedAt = 0
```

For background, most keywords are English, e.g. `var =` and  `means= `

**Comment by mcneale** [comment]
Maybe there should be a umxGlossary()?

**Comment by tbates** [comment]
:-)
maybe
```R
umxGuess("residuals")
```
> Perhaps you want `umx_residualize`?

I was just trying to understand an Mplus model (never can remember their syntax) and tried the `mplus2lavaan.modelSyntax` function, which didn't quite do it, but then running it into umxRAM() to get a plot... Kind of got there in the end.
